/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina.visualizar;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import oficina.classes.Carro;
import oficina.classes.ConexaoBd;
import oficina.classes.OrdemDeServico;
import oficina.classes.PessoaFisica;

/**
 *
 * @author Rich
 */
public class VisualizaPessoaFisica extends javax.swing.JFrame {

    /**
     * Creates new form VisualizaPessoaFisica
     */
    public VisualizaPessoaFisica(PessoaFisica cliente) {
                
        initComponents();
        this.cliente = cliente;
        this.setLocationRelativeTo(null);
        lbNomeText.setText(cliente.getNome());
        lbRgText.setText(cliente.getRG());
        lbCpfText.setText((cliente.getCPF()));
        lbRuaText.setText(cliente.getRua());
        lbNumeroText.setText(cliente.getEndNumero());
        lbCepText.setText(cliente.getCEP());
        lbBairroText.setText(cliente.getBairro());
        lbCidadeText.setText(cliente.getCidade());
        lbEstadoText.setText(cliente.getEstado());
        lbTelefoneText.setText(cliente.getNumResidencial());
        lbCelularText.setText(cliente.getNumCelular());
        lbEmailText.setText(cliente.getEmail());
        taObsText.setText(cliente.getObservacoes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelInfoRow1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbNomeText = new javax.swing.JLabel();
        panelInfoRow2 = new javax.swing.JPanel();
        lbRg = new javax.swing.JLabel();
        lbRgText = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbCpfText = new javax.swing.JLabel();
        panelInfoRow3 = new javax.swing.JPanel();
        lbRua = new javax.swing.JLabel();
        lbRuaText = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        lbNumeroText = new javax.swing.JLabel();
        lbCep = new javax.swing.JLabel();
        lbCepText = new javax.swing.JLabel();
        panelInfoRow4 = new javax.swing.JPanel();
        lbBairro = new javax.swing.JLabel();
        lbBairroText = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbCidadeText = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        lbEstadoText = new javax.swing.JLabel();
        panelInfoRow5 = new javax.swing.JPanel();
        lbTelefone = new javax.swing.JLabel();
        lbTelefoneText = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        lbCelularText = new javax.swing.JLabel();
        panelInfoRow6 = new javax.swing.JPanel();
        lbEmail = new javax.swing.JLabel();
        lbEmailText = new javax.swing.JLabel();
        panelInfoRow7 = new javax.swing.JPanel();
        lbObs = new javax.swing.JLabel();
        panelInfoRow8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObsText = new javax.swing.JTextArea();
        panelBotoes = new javax.swing.JPanel();
        btCarro = new javax.swing.JButton();
        btOS = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualização de Pessoa Física");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        lbTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbTitulo.setText("Visualização de Pessoa Física");
        panelTitulo.add(lbTitulo);

        getContentPane().add(panelTitulo);

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setText("Nome: ");
        panelInfoRow1.add(lbNome);
        panelInfoRow1.add(lbNomeText);

        getContentPane().add(panelInfoRow1);

        lbRg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRg.setText("RG: ");
        panelInfoRow2.add(lbRg);
        panelInfoRow2.add(lbRgText);

        lbCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCpf.setText("CPF: ");
        panelInfoRow2.add(lbCpf);
        panelInfoRow2.add(lbCpfText);

        getContentPane().add(panelInfoRow2);

        lbRua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRua.setText("Rua: ");
        panelInfoRow3.add(lbRua);
        panelInfoRow3.add(lbRuaText);

        lbNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNumero.setText("Numero: ");
        panelInfoRow3.add(lbNumero);
        panelInfoRow3.add(lbNumeroText);

        lbCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCep.setText("CEP: ");
        panelInfoRow3.add(lbCep);
        panelInfoRow3.add(lbCepText);

        getContentPane().add(panelInfoRow3);

        lbBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBairro.setText("Bairro: ");
        panelInfoRow4.add(lbBairro);
        panelInfoRow4.add(lbBairroText);

        lbCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCidade.setText("Cidade: ");
        panelInfoRow4.add(lbCidade);
        panelInfoRow4.add(lbCidadeText);

        lbEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEstado.setText("Estado: ");
        panelInfoRow4.add(lbEstado);
        panelInfoRow4.add(lbEstadoText);

        getContentPane().add(panelInfoRow4);

        lbTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTelefone.setText("Telefone: ");
        panelInfoRow5.add(lbTelefone);
        panelInfoRow5.add(lbTelefoneText);

        lbCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCelular.setText("Celular: ");
        panelInfoRow5.add(lbCelular);
        panelInfoRow5.add(lbCelularText);

        getContentPane().add(panelInfoRow5);

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmail.setText("Email: ");
        panelInfoRow6.add(lbEmail);
        panelInfoRow6.add(lbEmailText);

        getContentPane().add(panelInfoRow6);

        lbObs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbObs.setText("Observações:");
        panelInfoRow7.add(lbObs);

        getContentPane().add(panelInfoRow7);

        taObsText.setEditable(false);
        taObsText.setColumns(35);
        taObsText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        taObsText.setLineWrap(true);
        taObsText.setRows(5);
        taObsText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taObsText);

        panelInfoRow8.add(jScrollPane1);

        getContentPane().add(panelInfoRow8);

        btCarro.setText("Ver Carros");
        btCarro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCarroActionPerformed(evt);
            }
        });
        panelBotoes.add(btCarro);

        btOS.setText("Ver OS");
        btOS.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btOSActionPerformed(evt);
            }
        });
        panelBotoes.add(btOS);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btSairActionPerformed(evt);
            }
        });
        panelBotoes.add(btSair);

        getContentPane().add(panelBotoes);

        jScrollPane2.setPreferredSize(new java.awt.Dimension(450, 100));

        tabela.setBackground(new java.awt.Color(204, 204, 204));
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {},
                {},
                {},
                {}
            },
            new String []
            {

            }
        ));
        tabela.setShowHorizontalLines(false);
        tabela.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabela);

        getContentPane().add(jScrollPane2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarroActionPerformed
        // TODO add your handling code here:
            tabelaOS = false;
            Carro carro;
            ConexaoBd bd = new ConexaoBd();
            try {this.carrosLista.clear();}catch(RuntimeException e){this.carrosLista = new ArrayList<Carro>();}
            this.carrosLista = bd.buscaCarroClienteFisico(this.cliente);
            Iterator<Carro> it = this.carrosLista.iterator();
            DefaultTableModel model = (DefaultTableModel)tabela.getModel(); 
            model.setNumRows(0);
            model.setColumnCount(3);
            model.setColumnIdentifiers(new Object[]{"Placa", "Modelo", "Ano"});
            Class<?> col_class = tabela.getColumnClass(0);
            tabela.setDefaultEditor(col_class, null);
            col_class = tabela.getColumnClass(1);
            tabela.setDefaultEditor(col_class, null);
            col_class = tabela.getColumnClass(2);
            tabela.setDefaultEditor(col_class, null);
            while(it.hasNext())
            {   carro = it.next();
                model.addRow(new Object[]{carro.getPlaca(), carro.getNomeModelo(), carro.getAno()});
            }
    }//GEN-LAST:event_btCarroActionPerformed

    private void btOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOSActionPerformed
        // TODO add your handling code here:
            tabelaOS = true;
            OrdemDeServico os;
            ConexaoBd bd = new ConexaoBd();
            try {this.osLista.clear();}catch(RuntimeException e){this.osLista = new ArrayList<OrdemDeServico>();}
            this.osLista = bd.buscaOSCliente(cliente.getCodCliente());
            Iterator<OrdemDeServico> it = this.osLista.iterator();
            DefaultTableModel model = (DefaultTableModel)tabela.getModel(); 
            model.setNumRows(0);
            model.setColumnCount(3);
            model.setColumnIdentifiers(new Object[]{"Numero da OS", "Carro", "Estado"});
            Class<?> col_class = tabela.getColumnClass(0);
            tabela.setDefaultEditor(col_class, null);
            col_class = tabela.getColumnClass(1);
            tabela.setDefaultEditor(col_class, null);
            col_class = tabela.getColumnClass(2);
            tabela.setDefaultEditor(col_class, null);
            while(it.hasNext())
            {   os = it.next();
                model.addRow(new Object[]{os.getCodigoOs(), os.getPlacaCarro(), os.getEstado()});
            }
    }//GEN-LAST:event_btOSActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount() == 2)
        {
            if(tabelaOS)
            {
                OrdemDeServico os = this.osLista.get(tabela.getSelectedRow());
                  new VisualizaOs(os).setVisible(true);
            }
        
            else
            {
                Carro carro = this.carrosLista.get(tabela.getSelectedRow());
               new VisualizaCarro(carro).setVisible(true);
            }
        }
    }//GEN-LAST:event_tabelaMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCarro;
    private javax.swing.JButton btOS;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbBairroText;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCelularText;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCepText;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCidadeText;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbCpfText;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailText;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstadoText;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeText;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbNumeroText;
    private javax.swing.JLabel lbObs;
    private javax.swing.JLabel lbRg;
    private javax.swing.JLabel lbRgText;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbRuaText;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTelefoneText;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelInfoRow1;
    private javax.swing.JPanel panelInfoRow2;
    private javax.swing.JPanel panelInfoRow3;
    private javax.swing.JPanel panelInfoRow4;
    private javax.swing.JPanel panelInfoRow5;
    private javax.swing.JPanel panelInfoRow6;
    private javax.swing.JPanel panelInfoRow7;
    private javax.swing.JPanel panelInfoRow8;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextArea taObsText;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
    private List<Carro> carrosLista;
    private List<OrdemDeServico> osLista;
    private PessoaFisica cliente;
    boolean tabelaOS;
}
