/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina.modal;

import java.util.Random;
import oficina.classes.Carro;
import oficina.classes.ConexaoBd;

/**
 *
 * @author Administrator
 */
public class buscaCarroModal extends javax.swing.JDialog
{

    /**
     * Creates new form buscaCarroModal
     */
    public buscaCarroModal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        
        this.setLocationRelativeTo(null);
        placa = null;
    }
    
    public String showDiag()
    {
        setVisible(true);
        return placa;
    }
    public int codCliente(){
        return this.codDono;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBuscaCarro = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelPlaca = new javax.swing.JPanel();
        lbPlaca = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        panelAlertaPlaca = new javax.swing.JPanel();
        lbAlertaPlaca = new javax.swing.JLabel();
        panelBuscarPlaca = new javax.swing.JPanel();
        btBuscarPlaca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Selecionar Carro");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelBuscaCarro.setBorder(javax.swing.BorderFactory.createTitledBorder("Selecionar carro:"));
        panelBuscaCarro.setLayout(new javax.swing.BoxLayout(panelBuscaCarro, javax.swing.BoxLayout.PAGE_AXIS));
        panelBuscaCarro.add(filler4);

        lbPlaca.setText("Placa do Carro: ");
        panelPlaca.add(lbPlaca);

        tfPlaca.setColumns(10);
        tfPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPlacaKeyTyped(evt);
            }
        });
        panelPlaca.add(tfPlaca);

        panelBuscaCarro.add(panelPlaca);

        lbAlertaPlaca.setForeground(new java.awt.Color(255, 0, 0));
        lbAlertaPlaca.setPreferredSize(new java.awt.Dimension(150, 14));
        panelAlertaPlaca.add(lbAlertaPlaca);

        panelBuscaCarro.add(panelAlertaPlaca);

        btBuscarPlaca.setText("OK");
        btBuscarPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarPlacaActionPerformed(evt);
            }
        });
        panelBuscarPlaca.add(btBuscarPlaca);

        panelBuscaCarro.add(panelBuscarPlaca);

        getContentPane().add(panelBuscaCarro);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfPlacaKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_tfPlacaKeyTyped
    {//GEN-HEADEREND:event_tfPlacaKeyTyped
        char caractere = evt.getKeyChar();

        if(tfPlaca.getText().length() > 7)
        evt.consume();

        else
        {
            if(Character.isAlphabetic(caractere))
            evt.setKeyChar(Character.toUpperCase(caractere));

            if(tfPlaca.getText().length() < 3
                && !Character.isAlphabetic(caractere))
            evt.consume();

            else if(tfPlaca.getText().length() == 3
                && Character.isDigit(caractere))
            tfPlaca.setText(tfPlaca.getText() + '-');

            else if(tfPlaca.getText().length() == 3
                && !Character.isDigit(caractere)
                && caractere != '-')
            evt.consume();

            else if(tfPlaca.getText().length() > 3
                && !Character.isDigit(caractere))
            evt.consume();
        }
    }//GEN-LAST:event_tfPlacaKeyTyped

    private void btBuscarPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarPlacaActionPerformed
        Random generator = new Random();
        ConexaoBd bd = new ConexaoBd();
        Carro c;
        if(tfPlaca.getText().length() == 8)
        {
            c = bd.buscaCarroPlaca(tfPlaca.getText());
            if(c != null)
            {
                placa = tfPlaca.getText().toString(); // mudar para VisualizaPessoaFisica(pfBusca) quando pfBusca conseguir ser retorno de busca no BD
                codDono = c.getCodDono();
                setVisible(false);
                this.dispose();
            }
            
            else
            {
                lbAlertaPlaca.setText("Carro não cadastrado.");
                placa = null;
            }
        }
        
        else if(tfPlaca.getText().length() == 0)
        {
            lbAlertaPlaca.setText("Informe uma placa.");
            placa = null;
        }
        
        else
        {
            lbAlertaPlaca.setText("Placa inválida.");
            placa = null;
        }
    }//GEN-LAST:event_btBuscarPlacaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(buscaCarroModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(buscaCarroModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(buscaCarroModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(buscaCarroModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                buscaCarroModal dialog = new buscaCarroModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarPlaca;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JLabel lbAlertaPlaca;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JPanel panelAlertaPlaca;
    private javax.swing.JPanel panelBuscaCarro;
    private javax.swing.JPanel panelBuscarPlaca;
    private javax.swing.JPanel panelPlaca;
    private javax.swing.JTextField tfPlaca;
    // End of variables declaration//GEN-END:variables
    private String placa;
    private int codDono;
}
