/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina.modal;

import oficina.classes.Servico;
import java.util.Random;
import oficina.classes.ConexaoBd;

/**
 *
 * @author Administrator
 */
public class formServicoModal extends javax.swing.JDialog
{

    /**
     * Creates new form FormServico
     */
    public formServicoModal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
        ConexaoBd bd = new ConexaoBd();
        bd.preencheCbMecanico(cbMecanico);
        this.setLocationRelativeTo(null);
    }
    
    public formServicoModal(java.awt.Frame parent, boolean modal, Servico s)
    {
        super(parent, modal);
        initComponents();
        
        ConexaoBd bd = new ConexaoBd();
        bd.preencheCbMecanico(cbMecanico);
        cbMecanico.setSelectedItem(s.getNomeMecanico());
       
        taDescr.setText(s.getNomeServico());
        tfPreco.setText(s.getPreco());
        tfPreco.setEnabled(false);
        
        
        this.setLocationRelativeTo(null);
    }
    
    public Servico showDiag()
    {
        setVisible(true);
        return serv;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCriarServiço = new javax.swing.JPanel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        panelDescrição = new javax.swing.JPanel();
        lbDescr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDescr = new javax.swing.JTextArea();
        panelPreco = new javax.swing.JPanel();
        lbPreco = new javax.swing.JLabel();
        tfPreco = new javax.swing.JFormattedTextField();
        panelMecanico = new javax.swing.JPanel();
        lbMecanico = new javax.swing.JLabel();
        cbMecanico = new javax.swing.JComboBox();
        panelAlerta = new javax.swing.JPanel();
        lbAlerta = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        btOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Serviço");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        panelCriarServiço.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviço:"));
        panelCriarServiço.setLayout(new javax.swing.BoxLayout(panelCriarServiço, javax.swing.BoxLayout.PAGE_AXIS));
        panelCriarServiço.add(filler4);

        lbDescr.setText("Descrição:");
        panelDescrição.add(lbDescr);

        taDescr.setColumns(20);
        taDescr.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        taDescr.setLineWrap(true);
        taDescr.setRows(5);
        taDescr.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taDescr);

        panelDescrição.add(jScrollPane1);

        panelCriarServiço.add(panelDescrição);

        lbPreco.setText("Preço:");
        panelPreco.add(lbPreco);

        tfPreco.setColumns(6);
        tfPreco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        panelPreco.add(tfPreco);

        panelCriarServiço.add(panelPreco);

        lbMecanico.setText("Mecânico:");
        panelMecanico.add(lbMecanico);

        panelMecanico.add(cbMecanico);

        panelCriarServiço.add(panelMecanico);

        lbAlerta.setForeground(new java.awt.Color(255, 0, 0));
        lbAlerta.setPreferredSize(new java.awt.Dimension(220, 14));
        panelAlerta.add(lbAlerta);

        panelCriarServiço.add(panelAlerta);

        btOk.setText("OK");
        btOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOkActionPerformed(evt);
            }
        });
        panelBotoes.add(btOk);

        panelCriarServiço.add(panelBotoes);

        getContentPane().add(panelCriarServiço);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOkActionPerformed
        if(taDescr.getText().length() == 0 || tfPreco.getText().length() == 0)
        {
            lbAlerta.setText("Todos os campos devem ser preenchidos.");
        }

        else
        {
            serv = new Servico(taDescr.getText(), 
                    tfPreco.getText(), 
                    cbMecanico.getSelectedItem().toString());
            ConexaoBd bd = new ConexaoBd();
            serv.setCodMecanico(bd.buscaCodMecanico(serv.getNomeMecanico()));
            
            setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_btOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(formServicoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(formServicoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(formServicoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(formServicoModal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                formServicoModal dialog = new formServicoModal(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOk;
    private javax.swing.JComboBox cbMecanico;
    private javax.swing.Box.Filler filler4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAlerta;
    private javax.swing.JLabel lbDescr;
    private javax.swing.JLabel lbMecanico;
    private javax.swing.JLabel lbPreco;
    private javax.swing.JPanel panelAlerta;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelCriarServiço;
    private javax.swing.JPanel panelDescrição;
    private javax.swing.JPanel panelMecanico;
    private javax.swing.JPanel panelPreco;
    private javax.swing.JTextArea taDescr;
    private javax.swing.JFormattedTextField tfPreco;
    // End of variables declaration//GEN-END:variables
    private Servico serv;
}
