/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina.unused;

import oficina.classes.StringPlacaException;
import oficina.classes.Carro;
import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import oficina.visualizar.VisualizaCarro;
import oficina.modal.buscaClienteModal;


/**
 *
 * @author carolinapascalecampos
 */
public class FormCarro extends javax.swing.JFrame {

    /**
     * Creates new form Carro
     */
    public FormCarro() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    private void verificaStringPlaca(String placa) throws StringPlacaException {
         
            if(placa.length() < 8)
                throw new StringPlacaException("Campo placa tem menos que 8 caracteres!");
            
            if(placa.codePointAt(0) < 'A' || placa.codePointAt(0) > 'Z' ){
                throw new StringPlacaException("O primeiro dígito da placa não é válido");  
            }
            
            if(placa.codePointAt(1) < 'A' || placa.codePointAt(1) > 'Z'){
                throw new StringPlacaException("O segundo dígito da placa não é válido");  
            }
            
            if(placa.codePointAt(2) < 'A' || placa.codePointAt(2) > 'Z'){
                throw new StringPlacaException("O terceiro dígito da placa não é válido");  
            }
            
            if(placa.codePointAt(3) != '-'){//o hifen nao esta no lugar correto
                throw new StringPlacaException("O quarto dígito da placa não é válido");  
            }
            
            if(placa.codePointAt(4) < '0' || placa.codePointAt(4) > '9'){
                throw new StringPlacaException("O quinto dígito da placa não é válido");  
            }
            
            if(placa.codePointAt(5) < '0' || placa.codePointAt(5) > '9'){
                throw new StringPlacaException("O sexto dígito da placa não é válido");  
            }
            
            if(placa.codePointAt(6) < '0' || placa.codePointAt(6) > '9'){
                throw new StringPlacaException("O sétimo dígito da placa não é válido");  
            }
            
            if(placa.codePointAt(7) < '0' || placa.codePointAt(7) > '9'){
                throw new StringPlacaException("O oitavo dígito da placa não é válido");
            }
           
    }
    
    public void verificaAno(int ano) throws RuntimeException{
        if(ano < 1950 || ano > 2016){ //se o ano nao estiver dentro do intervalo valido
                throw new RuntimeException("O ano informado não é válido"); 
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelTitulo = new javax.swing.JPanel();
        lbIcone = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        btSelecionarCliente = new javax.swing.JButton();
        lbClienteText = new javax.swing.JLabel();
        panelPlacaRow1 = new javax.swing.JPanel();
        lbPlaca = new javax.swing.JLabel();
        tfPlaca = new javax.swing.JTextField();
        lbPlacaEx = new javax.swing.JLabel();
        panelPlacaAlertaHolder = new javax.swing.JPanel();
        lbPlacaAlerta = new javax.swing.JLabel();
        panelMarca = new javax.swing.JPanel();
        lbMarca = new javax.swing.JLabel();
        cboxMarca = new javax.swing.JComboBox();
        panelModelo = new javax.swing.JPanel();
        lbModelo = new javax.swing.JLabel();
        cboxModelo = new javax.swing.JComboBox();
        panelCor = new javax.swing.JPanel();
        lbCor = new javax.swing.JLabel();
        cboxCor = new javax.swing.JComboBox();
        panelAnoRow1 = new javax.swing.JPanel();
        lbAno = new javax.swing.JLabel();
        tfAno = new javax.swing.JTextField();
        lbAnoEx = new javax.swing.JLabel();
        panelAnoAlertaHolder = new javax.swing.JPanel();
        lbAnoAlerta = new javax.swing.JLabel();
        panelObs = new javax.swing.JPanel();
        lbObs = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObs = new javax.swing.JTextArea();
        panelBotoes = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Carro");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        lbIcone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbIcone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/icon-veiculos.png"))); // NOI18N
        panelTitulo.add(lbIcone);

        lbTitulo.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbTitulo.setText("Cadastro de Carro");
        panelTitulo.add(lbTitulo);

        getContentPane().add(panelTitulo);

        panelCliente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btSelecionarCliente.setText("Cliente: ");
        btSelecionarCliente.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btSelecionarClienteMouseClicked(evt);
            }
        });
        panelCliente.add(btSelecionarCliente);

        lbClienteText.setText("NÃO INFORMADO");
        lbClienteText.setPreferredSize(new java.awt.Dimension(150, 14));
        panelCliente.add(lbClienteText);

        getContentPane().add(panelCliente);

        panelPlacaRow1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbPlaca.setText("Placa:");
        lbPlaca.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelPlacaRow1.add(lbPlaca);

        tfPlaca.setColumns(10);
        tfPlaca.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfPlaca.setToolTipText("Preencha a placa do carro, exemplo: AKG-1529");
        tfPlaca.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfPlacaKeyTyped(evt);
            }
        });
        panelPlacaRow1.add(tfPlaca);

        lbPlacaEx.setForeground(new java.awt.Color(102, 102, 102));
        lbPlacaEx.setText("ex: AAA-1234");
        lbPlacaEx.setOpaque(true);
        panelPlacaRow1.add(lbPlacaEx);

        getContentPane().add(panelPlacaRow1);

        panelPlacaAlertaHolder.setPreferredSize(new java.awt.Dimension(169, 24));
        panelPlacaAlertaHolder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbPlacaAlerta.setForeground(new java.awt.Color(255, 0, 0));
        panelPlacaAlertaHolder.add(lbPlacaAlerta);

        getContentPane().add(panelPlacaAlertaHolder);

        panelMarca.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbMarca.setText("Marca: ");
        panelMarca.add(lbMarca);

        cboxMarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banco de Dados" }));
        panelMarca.add(cboxMarca);

        getContentPane().add(panelMarca);

        panelModelo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbModelo.setText("Modelo: ");
        panelModelo.add(lbModelo);

        cboxModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Banco de Dados" }));
        panelModelo.add(cboxModelo);

        getContentPane().add(panelModelo);

        panelCor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbCor.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbCor.setText("Cor:");
        lbCor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        panelCor.add(lbCor);

        cboxCor.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Preto", "Branco", "Cinza", "Vermelho", "Azul", "Verde" }));
        panelCor.add(cboxCor);

        getContentPane().add(panelCor);

        panelAnoRow1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbAno.setText("Ano: ");
        panelAnoRow1.add(lbAno);

        tfAno.setColumns(5);
        tfAno.setToolTipText("Preencha com o ano de fabricação do carro");
        tfAno.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                tfAnoKeyTyped(evt);
            }
        });
        panelAnoRow1.add(tfAno);

        lbAnoEx.setForeground(new java.awt.Color(102, 102, 102));
        lbAnoEx.setText("ex: 1984");
        lbAnoEx.setOpaque(true);
        panelAnoRow1.add(lbAnoEx);

        getContentPane().add(panelAnoRow1);

        panelAnoAlertaHolder.setPreferredSize(new java.awt.Dimension(169, 24));
        panelAnoAlertaHolder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbAnoAlerta.setForeground(new java.awt.Color(255, 0, 0));
        panelAnoAlertaHolder.add(lbAnoAlerta);

        getContentPane().add(panelAnoAlertaHolder);

        panelObs.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbObs.setText("Observações:");
        panelObs.add(lbObs);

        taObs.setColumns(20);
        taObs.setLineWrap(true);
        taObs.setRows(5);
        taObs.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taObs);

        panelObs.add(jScrollPane1);

        getContentPane().add(panelObs);

        btCadastrar.setText("Cadastrar");
        btCadastrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btCadastrarMouseClicked(evt);
            }
        });
        panelBotoes.add(btCadastrar);

        btLimpar.setText("Limpar");
        btLimpar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btLimparMouseClicked(evt);
            }
        });
        panelBotoes.add(btLimpar);

        btVisualizar.setText("Visualizar");
        btVisualizar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btVisualizarMouseClicked(evt);
            }
        });
        panelBotoes.add(btVisualizar);

        getContentPane().add(panelBotoes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadastrarMouseClicked
        c = new Carro();
        int flagCampos = 1; //caso todos os campos estejam corretos a flag sera igual a 1
        
        //Se cliente é null, não cadastra. Se não é null, está certo pela função
        if(clienteCpfCnpj == null)
        {
            lbClienteText.setForeground(Color.red);
            flagCampos = 0;
        }
        
        //Se a placa nao foi informada e preciso pedir ao usuario que a preencha
        if(tfPlaca.getText().trim().isEmpty())
        {
            lbPlacaAlerta.setText("Por favor, preencha este campo!");
            flagCampos = 0;
        }
        
        else
        {
            //Apaga label de alerta
            lbPlacaAlerta.setText("");
      
            try{ verificaStringPlaca(tfPlaca.getText());}

            catch(StringPlacaException e){
                lbPlacaAlerta.setText(e.getMsgErro());
                flagCampos = 0;
            }
        }
        
        //Se o ano nao foi informado e preciso pedir ao usuario que o preencha
        if(tfAno.getText().trim().isEmpty())
        {
            lbAnoAlerta.setText("Por favor, preencha este campo!");
            flagCampos = 0;
        }
        
        else //o ano foi informado pelo usuario
        {
            lbAnoAlerta.setText("");
            
            try{ verificaAno(Integer.parseInt(tfAno.getText()));} //guarda no objeto o ano informado pelo usuario
            catch(RuntimeException e){
                lbAnoAlerta.setText(e.getMessage());
                flagCampos = 0;
            }
        }
        
        //caso todos os campos tenham sido preenchidos corretamente
        if(flagCampos == 1){
            //guarda no objeto a cor informada pelo usuario
            c.setCodDono(clienteCpfCnpj);
            c.setPlaca(tfPlaca.getText());
            c.setMarca(cboxMarca.getSelectedItem().toString());
            c.setModelo(cboxModelo.getSelectedItem().toString());
            c.setCor(cboxCor.getSelectedItem().toString());
            c.setAno(tfAno.getText());
            c.setObservacoes(taObs.getText());
            
            lbClienteText.setText("NÃO INFORMADO");
            lbClienteText.setForeground(Color.black);
            clienteCpfCnpj = null;      
            tfPlaca.setText(null);
            tfAno.setText(null);
            lbPlacaAlerta.setText("");
            lbAnoAlerta.setText("");
            taObs.setText("");
            cboxMarca.setSelectedIndex(0);
            cboxModelo.setSelectedIndex(0);
            cboxCor.setSelectedIndex(0);
            
            JOptionPane.showMessageDialog(null, "Carro cadastrado com sucesso!");
        }
    }//GEN-LAST:event_btCadastrarMouseClicked

    private void btVisualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVisualizarMouseClicked
        // TODO add your handling code here:
        VisualizaCarro v;
        
        if(c != null){
            v = new VisualizaCarro(c);
            v.setVisible(true);
        }
        
        else{
          JOptionPane.showMessageDialog(null, "Você deve cadastrar o carro antes de visualizar");
        }
    }//GEN-LAST:event_btVisualizarMouseClicked

    private void btLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btLimparMouseClicked
        //Limpa todos os campos
        lbClienteText.setText("NÃO INFORMADO");
        lbClienteText.setForeground(Color.black);
        clienteCpfCnpj = null;      
        tfPlaca.setText(null);
        tfAno.setText(null);
        lbPlacaAlerta.setText("");
        lbAnoAlerta.setText("");
        taObs.setText("");
        cboxMarca.setSelectedIndex(0);
        cboxModelo.setSelectedIndex(0);
        cboxCor.setSelectedIndex(0);
    }//GEN-LAST:event_btLimparMouseClicked

    private void tfAnoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfAnoKeyTyped
        // TODO add your handling code here:
        char caractere = evt.getKeyChar();
        
        if(!(Character.isDigit(caractere) 
                || caractere == KeyEvent.VK_BACK_SPACE 
                || caractere == KeyEvent.VK_DELETE) 
                || tfAno.getText().length() > 3)
            evt.consume();
    }//GEN-LAST:event_tfAnoKeyTyped

    private void tfPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPlacaKeyTyped
        char caractere = evt.getKeyChar();
        
        if(tfPlaca.getText().length() > 7)
            evt.consume();
        
        else
        {
            if(Character.isAlphabetic(caractere))
                evt.setKeyChar(Character.toUpperCase(caractere));

            if(tfPlaca.getText().length() < 3 
                    && !Character.isAlphabetic(caractere))
                evt.consume();

            else if(tfPlaca.getText().length() == 3 
                   && Character.isDigit(caractere))
               tfPlaca.setText(tfPlaca.getText() + '-');

            else if(tfPlaca.getText().length() == 3 
                    && !Character.isDigit(caractere)
                    && caractere != '-')
                evt.consume();
            
            else if(tfPlaca.getText().length() > 3 
                    && !Character.isDigit(caractere))
                evt.consume();
        }
    }//GEN-LAST:event_tfPlacaKeyTyped

    private void btSelecionarClienteMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btSelecionarClienteMouseClicked
    {//GEN-HEADEREND:event_btSelecionarClienteMouseClicked
        buscaClienteModal dlg = new buscaClienteModal(this, true);
        clienteCpfCnpj = dlg.showDiag();

        if(clienteCpfCnpj != null)
        {
            lbClienteText.setText(clienteCpfCnpj);
            lbClienteText.setForeground(Color.black);
        }
        
        else
            lbClienteText.setForeground(Color.red);
    }//GEN-LAST:event_btSelecionarClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSelecionarCliente;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JComboBox cboxCor;
    private javax.swing.JComboBox cboxMarca;
    private javax.swing.JComboBox cboxModelo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbAno;
    private javax.swing.JLabel lbAnoAlerta;
    private javax.swing.JLabel lbAnoEx;
    private javax.swing.JLabel lbClienteText;
    private javax.swing.JLabel lbCor;
    private javax.swing.JLabel lbIcone;
    private javax.swing.JLabel lbMarca;
    private javax.swing.JLabel lbModelo;
    private javax.swing.JLabel lbObs;
    private javax.swing.JLabel lbPlaca;
    private javax.swing.JLabel lbPlacaAlerta;
    private javax.swing.JLabel lbPlacaEx;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelAnoAlertaHolder;
    private javax.swing.JPanel panelAnoRow1;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelCor;
    private javax.swing.JPanel panelMarca;
    private javax.swing.JPanel panelModelo;
    private javax.swing.JPanel panelObs;
    private javax.swing.JPanel panelPlacaAlertaHolder;
    private javax.swing.JPanel panelPlacaRow1;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextArea taObs;
    private javax.swing.JTextField tfAno;
    private javax.swing.JTextField tfPlaca;
    // End of variables declaration//GEN-END:variables
    private Carro c;
    private String clienteCpfCnpj;
}
