/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina;

import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;

/**
 *
 * @author filiperocchi
 */
public class FormLogin extends javax.swing.JFrame {

    /**
     * Creates new form Formlogin
     */
    public FormLogin() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelTitulo = new javax.swing.JPanel();
        lbIconeLogin = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        panelUsuarioRow1 = new javax.swing.JPanel();
        lbNomeUsuario = new javax.swing.JLabel();
        tfNomeUsuario = new javax.swing.JTextField();
        panelInfoAlerta1Holder = new javax.swing.JPanel();
        lbInfoAlerta1 = new javax.swing.JLabel();
        panelSenhaRow1 = new javax.swing.JPanel();
        lbSenha = new javax.swing.JLabel();
        jpSenha = new javax.swing.JPasswordField();
        panelInfoAlerta2Holder = new javax.swing.JPanel();
        lbInfoAlerta2 = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        btEntrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setMinimumSize(new java.awt.Dimension(330, 300));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        lbIconeLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/login.png"))); // NOI18N
        panelTitulo.add(lbIconeLogin);

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setText("Login");
        panelTitulo.add(lbTitulo);

        getContentPane().add(panelTitulo);

        panelUsuarioRow1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        lbNomeUsuario.setText("Usuário:");
        panelUsuarioRow1.add(lbNomeUsuario);

        tfNomeUsuario.setColumns(20);
        tfNomeUsuario.addInputMethodListener(new java.awt.event.InputMethodListener()
        {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt)
            {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt)
            {
                tfNomeUsuarioInputMethodTextChanged(evt);
            }
        });
        panelUsuarioRow1.add(tfNomeUsuario);

        getContentPane().add(panelUsuarioRow1);

        panelInfoAlerta1Holder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));
        panelInfoAlerta1Holder.add(lbInfoAlerta1);

        getContentPane().add(panelInfoAlerta1Holder);

        panelSenhaRow1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));

        lbSenha.setText("Senha:   ");
        panelSenhaRow1.add(lbSenha);

        jpSenha.setColumns(20);
        jpSenha.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jpSenhaActionPerformed(evt);
            }
        });
        panelSenhaRow1.add(jpSenha);

        getContentPane().add(panelSenhaRow1);

        panelInfoAlerta2Holder.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 5));
        panelInfoAlerta2Holder.add(lbInfoAlerta2);

        getContentPane().add(panelInfoAlerta2Holder);

        btEntrar.setFont(new java.awt.Font("Cantarell", 0, 20)); // NOI18N
        btEntrar.setText("Entrar");
        btEntrar.setToolTipText("");
        btEntrar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btEntrarMouseClicked(evt);
            }
        });
        btEntrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btEntrarActionPerformed(evt);
            }
        });
        panelBotoes.add(btEntrar);

        getContentPane().add(panelBotoes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNomeUsuarioInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tfNomeUsuarioInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeUsuarioInputMethodTextChanged

    private void btEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEntrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btEntrarActionPerformed

    private void btEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btEntrarMouseClicked
        // TODO add your handling code here:
        //verifica no BD se ha o nome e senha cadastrados
        //se nao houver indica no lbInfoAlerta1 para nome de usuario
        //e no lbInfoAlerta2 para senha
        Funcionario f = new Funcionario();
        f.setCodFuncionario(tfNomeUsuario.getText());
        f.setSenha(Arrays.toString(jpSenha.getPassword()));
        JOptionPane.showMessageDialog(null, "Autenticado com sucesso.");
        this.dispose(); //trocar para abrir o menu
        MenuPrincipal m = new MenuPrincipal(f);
        m.setVisible(true);
    }//GEN-LAST:event_btEntrarMouseClicked

    private void jpSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEntrar;
    private javax.swing.JPasswordField jpSenha;
    private javax.swing.JLabel lbIconeLogin;
    private javax.swing.JLabel lbInfoAlerta1;
    private javax.swing.JLabel lbInfoAlerta2;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbSenha;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelInfoAlerta1Holder;
    private javax.swing.JPanel panelInfoAlerta2Holder;
    private javax.swing.JPanel panelSenhaRow1;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelUsuarioRow1;
    private javax.swing.JTextField tfNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
