/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina;

import java.awt.Color;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Filipe
 */
public class FormOs extends javax.swing.JFrame {

    /**
     * Creates new form formOS
     */
    public FormOs() {
        initComponents();
        this.setLocationRelativeTo(null);
        valor = 0;
    }
    
    public FormOs(OrdemDeServico osAlterada) { // GAMBETA PRA GUARDAR OS ALTERADA, NÃO DEVE SER NECESSARIO COM BD
        initComponents();
        this.setLocationRelativeTo(null);
        this.os = osAlterada;
        valor = 0;
    }

    private void calcularTotal()
    {
        DefaultListModel d = (DefaultListModel) lServicos.getModel();
        valor = 0;
        
        for(int i = 0; i < d.getSize(); i++)
        {
            valor += Double.parseDouble(((Servico) d.elementAt(i)).getPreco());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel4 = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelHolder = new javax.swing.JPanel();
        panelInfo = new javax.swing.JPanel();
        panelCodigo = new javax.swing.JPanel();
        lbCodigo = new javax.swing.JLabel();
        lbCodigoText = new javax.swing.JLabel();
        panelCarro = new javax.swing.JPanel();
        btSelecionarCarro = new javax.swing.JButton();
        lbCarroText = new javax.swing.JLabel();
        panelCliente = new javax.swing.JPanel();
        lbCliente = new javax.swing.JLabel();
        lbClienteText = new javax.swing.JLabel();
        panelTipo = new javax.swing.JPanel();
        lbTipo = new javax.swing.JLabel();
        cboxTipo = new javax.swing.JComboBox();
        panelEstado = new javax.swing.JPanel();
        lbEstado = new javax.swing.JLabel();
        cboxEstado = new javax.swing.JComboBox();
        panelKmEntrada = new javax.swing.JPanel();
        lbKmEntrada = new javax.swing.JLabel();
        tfKmEntrada = new javax.swing.JTextField();
        panelKmSaida = new javax.swing.JPanel();
        lbKmSaida = new javax.swing.JLabel();
        tfKmSaida = new javax.swing.JTextField();
        panelDataInicio = new javax.swing.JPanel();
        lbDataInicio = new javax.swing.JLabel();
        tfDataInicio = new javax.swing.JFormattedTextField();
        panelHoraInicio = new javax.swing.JPanel();
        lbHoraInicio = new javax.swing.JLabel();
        tfHoraInicio = new javax.swing.JFormattedTextField();
        lbHoraInicioEx = new javax.swing.JLabel();
        panelDataFim = new javax.swing.JPanel();
        lbDataFim = new javax.swing.JLabel();
        tfDataFim = new javax.swing.JFormattedTextField();
        panelHoraFim = new javax.swing.JPanel();
        lbHoraFim = new javax.swing.JLabel();
        tfHoraFim = new javax.swing.JFormattedTextField();
        tfHoraFimEx = new javax.swing.JLabel();
        panelAlerta = new javax.swing.JPanel();
        lbAlerta = new javax.swing.JLabel();
        panelHolderServicos = new javax.swing.JPanel();
        panelServicos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lServicos = new javax.swing.JList();
        panelBotoesLista = new javax.swing.JPanel();
        btAdd = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        panelValor = new javax.swing.JPanel();
        lbValor = new javax.swing.JLabel();
        lbValorText = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btVisualizar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Ordem de Serviço");
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        lbTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTitulo.setText("Cadastro de Ordem de Serviço");
        panelTitulo.add(lbTitulo);

        getContentPane().add(panelTitulo);

        panelHolder.setLayout(new javax.swing.BoxLayout(panelHolder, javax.swing.BoxLayout.LINE_AXIS));

        panelInfo.setLayout(new javax.swing.BoxLayout(panelInfo, javax.swing.BoxLayout.PAGE_AXIS));

        panelCodigo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbCodigo.setText("Código:");
        panelCodigo.add(lbCodigo);

        lbCodigoText.setPreferredSize(new java.awt.Dimension(60, 14));
        panelCodigo.add(lbCodigoText);

        panelInfo.add(panelCodigo);

        panelCarro.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        btSelecionarCarro.setText("Carro:");
        btSelecionarCarro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btSelecionarCarroActionPerformed(evt);
            }
        });
        panelCarro.add(btSelecionarCarro);

        lbCarroText.setText("NÃO INFORMADO");
        lbCarroText.setPreferredSize(new java.awt.Dimension(150, 14));
        panelCarro.add(lbCarroText);

        panelInfo.add(panelCarro);

        panelCliente.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbCliente.setText("Cliente:");
        panelCliente.add(lbCliente);

        lbClienteText.setText("NÃO INFORMADO");
        lbClienteText.setPreferredSize(new java.awt.Dimension(170, 14));
        panelCliente.add(lbClienteText);

        panelInfo.add(panelCliente);

        panelTipo.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbTipo.setText("Tipo: ");
        panelTipo.add(lbTipo);

        cboxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Revisão", "Revisão mais Problema", "Problema", "Retorno" }));
        panelTipo.add(cboxTipo);

        panelInfo.add(panelTipo);

        panelEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbEstado.setText("Estado: ");
        panelEstado.add(lbEstado);

        cboxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pendente para orçamento", "Pendente para aprovação", "Em atendimento", "Pendente pra pagamento", "Finalizada", "Cancelada" }));
        cboxEstado.setEnabled(false);
        panelEstado.add(cboxEstado);

        panelInfo.add(panelEstado);

        panelKmEntrada.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbKmEntrada.setText("Quilometragem de Entrada: ");
        panelKmEntrada.add(lbKmEntrada);

        tfKmEntrada.setColumns(10);
        panelKmEntrada.add(tfKmEntrada);

        panelInfo.add(panelKmEntrada);

        panelKmSaida.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbKmSaida.setText("Quilometragem de Saída:     ");
        panelKmSaida.add(lbKmSaida);

        tfKmSaida.setColumns(10);
        tfKmSaida.setEnabled(false);
        panelKmSaida.add(tfKmSaida);

        panelInfo.add(panelKmSaida);

        panelDataInicio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbDataInicio.setText("Data de Início:");
        panelDataInicio.add(lbDataInicio);

        tfDataInicio.setColumns(10);
        tfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        panelDataInicio.add(tfDataInicio);

        panelInfo.add(panelDataInicio);

        panelHoraInicio.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbHoraInicio.setText("Horário de Início: ");
        panelHoraInicio.add(lbHoraInicio);

        tfHoraInicio.setColumns(6);
        try
        {
            tfHoraInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        panelHoraInicio.add(tfHoraInicio);

        lbHoraInicioEx.setForeground(new java.awt.Color(102, 102, 102));
        lbHoraInicioEx.setText("ex: 18:00");
        panelHoraInicio.add(lbHoraInicioEx);

        panelInfo.add(panelHoraInicio);

        panelDataFim.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbDataFim.setText("Data de Fim:");
        panelDataFim.add(lbDataFim);

        tfDataFim.setColumns(10);
        tfDataFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        tfDataFim.setEnabled(false);
        panelDataFim.add(tfDataFim);

        panelInfo.add(panelDataFim);

        panelHoraFim.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbHoraFim.setText("Horário de Fim:    ");
        panelHoraFim.add(lbHoraFim);

        tfHoraFim.setColumns(6);
        try
        {
            tfHoraFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex)
        {
            ex.printStackTrace();
        }
        tfHoraFim.setText("");
        tfHoraFim.setEnabled(false);
        panelHoraFim.add(tfHoraFim);

        tfHoraFimEx.setForeground(new java.awt.Color(102, 102, 102));
        tfHoraFimEx.setText("ex: 18:30");
        panelHoraFim.add(tfHoraFimEx);

        panelInfo.add(panelHoraFim);

        panelAlerta.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbAlerta.setForeground(new java.awt.Color(255, 0, 0));
        lbAlerta.setPreferredSize(new java.awt.Dimension(280, 14));
        panelAlerta.add(lbAlerta);

        panelInfo.add(panelAlerta);

        panelHolder.add(panelInfo);

        panelServicos.setBorder(javax.swing.BorderFactory.createTitledBorder("Serviços:"));
        panelServicos.setLayout(new javax.swing.BoxLayout(panelServicos, javax.swing.BoxLayout.PAGE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(160, 260));

        lServicos.setModel(new DefaultListModel<Servico>()
        );
        lServicos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lServicos.setVisibleRowCount(10);
        lServicos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lServicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(lServicos);

        panelServicos.add(jScrollPane1);

        panelBotoesLista.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        btAdd.setText("Adicionar");
        btAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btAddActionPerformed(evt);
            }
        });
        panelBotoesLista.add(btAdd);

        btDel.setText("Remover");
        btDel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btDelActionPerformed(evt);
            }
        });
        panelBotoesLista.add(btDel);

        panelServicos.add(panelBotoesLista);

        panelValor.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbValor.setText("Valor total:");
        panelValor.add(lbValor);

        lbValorText.setText("R$ 0,00");
        lbValorText.setPreferredSize(new java.awt.Dimension(60, 14));
        panelValor.add(lbValorText);

        panelServicos.add(panelValor);

        panelHolderServicos.add(panelServicos);

        panelHolder.add(panelHolderServicos);

        getContentPane().add(panelHolder);

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btCadastrarActionPerformed(evt);
            }
        });
        panelBotoes.add(btCadastrar);

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btLimparActionPerformed(evt);
            }
        });
        panelBotoes.add(btLimpar);

        btVisualizar.setText("Visualizar");
        btVisualizar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btVisualizarActionPerformed(evt);
            }
        });
        panelBotoes.add(btVisualizar);

        getContentPane().add(panelBotoes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btDelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btDelActionPerformed
    {//GEN-HEADEREND:event_btDelActionPerformed
        int selectedIndex = lServicos.getSelectedIndex();
        DefaultListModel d = (DefaultListModel) lServicos.getModel();
        
        if(selectedIndex != -1)
        {
            d.remove(selectedIndex);
            calcularTotal();
            lbValorText.setText("R$ " + Integer.toString(valor) + ",00");
        }
    }//GEN-LAST:event_btDelActionPerformed

    private void btAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btAddActionPerformed
    {//GEN-HEADEREND:event_btAddActionPerformed
        formServicoModal dlg = new formServicoModal(this, true);
        Servico servicoTemp = dlg.showDiag();
        
        if(servicoTemp != null)
        {
            DefaultListModel d = (DefaultListModel) lServicos.getModel();
            d.addElement(servicoTemp);
            
            calcularTotal();
            lbValorText.setText("R$ " + Integer.toString(valor) + ",00");
        }
    }//GEN-LAST:event_btAddActionPerformed

    private void btSelecionarCarroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btSelecionarCarroActionPerformed
    {//GEN-HEADEREND:event_btSelecionarCarroActionPerformed
        buscaCarroModal dlg = new buscaCarroModal(this, true);
        placa = dlg.showDiag();
        
        if(placa != null)
        {
            lbCarroText.setText(placa);
            lbCarroText.setForeground(Color.black);
            lbClienteText.setText("cliente dono atual do carro (bd)");
            //buscar dono atual do carro
        }
        
        else
            lbCarroText.setForeground(Color.red);
    }//GEN-LAST:event_btSelecionarCarroActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btLimparActionPerformed
    {//GEN-HEADEREND:event_btLimparActionPerformed
        lbAlerta.setText(null);
        lbKmEntrada.setForeground(Color.black);
        lbDataInicio.setForeground(Color.black);
        lbHoraInicio.setForeground(Color.black);
        lbCarroText.setForeground(Color.black);
        lbClienteText.setForeground(Color.black);
            
        tfKmEntrada.setText("");
        tfDataInicio.setText("");
        tfHoraInicio.setText("");
        lbCarroText.setText("NÃO INFORMADO");
        placa = null;
        lbClienteText.setText("NÃO INFORMADO");
        clienteCpfCnpj = null;
        cboxTipo.setSelectedIndex(0);
        
        DefaultListModel d = (DefaultListModel) lServicos.getModel();

        while(!d.isEmpty())
        {
            d.remove(0);
        };
    }//GEN-LAST:event_btLimparActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btCadastrarActionPerformed
    {//GEN-HEADEREND:event_btCadastrarActionPerformed
        if(tfKmEntrada.getText().equals("") || tfDataInicio.getText().equals("") 
                || tfHoraInicio.getText().equals("  :  ")
                || placa == null) // || clienteCpfCnpj == null
        {
            lbAlerta.setText("Por favor, preencha os campos destacados em vermelho.");
            
            if(tfKmEntrada.getText().equals(""))
                lbKmEntrada.setForeground(Color.red);
            else
                lbKmEntrada.setForeground(Color.black);

            if(tfDataInicio.getText().equals(""))
                lbDataInicio.setForeground(Color.red);
            else
                lbDataInicio.setForeground(Color.black);

            if(tfHoraInicio.getText().equals("  :  "))
                lbHoraInicio.setForeground(Color.red);
            else
                lbHoraInicio.setForeground(Color.black);
            
            if(placa == null)
                lbCarroText.setForeground(Color.red);
            else
                lbCarroText.setForeground(Color.black);
            
            //if cliente não informado etc
        }
        
        else
        {
            lbAlerta.setText(null);
            lbKmEntrada.setForeground(Color.black);
            lbDataInicio.setForeground(Color.black);
            lbHoraInicio.setForeground(Color.black);
            lbCarroText.setForeground(Color.black);
            lbClienteText.setForeground(Color.black);
            
            os = new OrdemDeServico();

            os.setCodigoOs(0);
            os.setPlacaCarro(placa);
            os.setCodCliente(clienteCpfCnpj);
            os.setKmEntrada(tfKmEntrada.getText());
            os.setKmSaida(tfKmSaida.getText());
            os.setDataInicio(tfDataInicio.getText());
            os.setDataFim(tfDataFim.getText());
            os.setHoraInicio(tfHoraInicio.getText());
            os.setHoraFim(tfHoraFim.getText());
            os.setTipo(cboxTipo.getSelectedItem().toString());
            os.setEstado(cboxEstado.getSelectedItem().toString());

            DefaultListModel d = (DefaultListModel) lServicos.getModel();

            while(!d.isEmpty())
            {
                os.servicos.add((Servico) d.remove(0));
            };
            
            tfKmEntrada.setText("");
            tfDataInicio.setText("");
            tfHoraInicio.setText("");
            lbCarroText.setText("NÃO INFORMADO");
            placa = null;
            lbClienteText.setText("NÃO INFORMADO");
            clienteCpfCnpj = null;
            cboxTipo.setSelectedIndex(0);
            
            JOptionPane.showMessageDialog(null, "Ordem de serviço cadastrada com sucesso!");
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btVisualizarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btVisualizarActionPerformed
    {//GEN-HEADEREND:event_btVisualizarActionPerformed
        if(os != null)
        {
            VisualizaOs v = new VisualizaOs(os);
            v.setVisible(true);
            this.dispose(); // GAMBETA PRA ALTERAÇÃO NA OS PELA VISUALIZAOS
        }

        else
        {
            JOptionPane.showMessageDialog(null, "Você deve cadastrar a ordem de serviço antes de visualizar");
        }
    }//GEN-LAST:event_btVisualizarActionPerformed

    private void lServicosMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lServicosMouseClicked
    {//GEN-HEADEREND:event_lServicosMouseClicked
        if(evt.getClickCount() == 2)
        {
            int index = lServicos.locationToIndex(evt.getPoint());
            
            if(index >= 0)
            {
                Servico servicoTempAntes = (Servico) lServicos.getModel().getElementAt(index);
                
                formServicoModal dlg = new formServicoModal(this, true, servicoTempAntes);
                Servico servicoTempDepois = dlg.showDiag();

                if(servicoTempDepois != null)
                {
                    DefaultListModel d = (DefaultListModel) lServicos.getModel();
                    d.set(d.indexOf(servicoTempAntes), servicoTempDepois);
                }
                
                calcularTotal();
                lbValorText.setText("R$ " + Integer.toString(valor) + ",00");
            }
        }
    }//GEN-LAST:event_lServicosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormOs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormOs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAdd;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSelecionarCarro;
    private javax.swing.JButton btVisualizar;
    private javax.swing.JComboBox cboxEstado;
    private javax.swing.JComboBox cboxTipo;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lServicos;
    private javax.swing.JLabel lbAlerta;
    private javax.swing.JLabel lbCarroText;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbClienteText;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbCodigoText;
    private javax.swing.JLabel lbDataFim;
    private javax.swing.JLabel lbDataInicio;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbHoraFim;
    private javax.swing.JLabel lbHoraInicio;
    private javax.swing.JLabel lbHoraInicioEx;
    private javax.swing.JLabel lbKmEntrada;
    private javax.swing.JLabel lbKmSaida;
    private javax.swing.JLabel lbTipo;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JLabel lbValor;
    private javax.swing.JLabel lbValorText;
    private javax.swing.JPanel panelAlerta;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelBotoesLista;
    private javax.swing.JPanel panelCarro;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelCodigo;
    private javax.swing.JPanel panelDataFim;
    private javax.swing.JPanel panelDataInicio;
    private javax.swing.JPanel panelEstado;
    private javax.swing.JPanel panelHolder;
    private javax.swing.JPanel panelHolderServicos;
    private javax.swing.JPanel panelHoraFim;
    private javax.swing.JPanel panelHoraInicio;
    private javax.swing.JPanel panelInfo;
    private javax.swing.JPanel panelKmEntrada;
    private javax.swing.JPanel panelKmSaida;
    private javax.swing.JPanel panelServicos;
    private javax.swing.JPanel panelTipo;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelValor;
    private javax.swing.JFormattedTextField tfDataFim;
    private javax.swing.JFormattedTextField tfDataInicio;
    private javax.swing.JFormattedTextField tfHoraFim;
    private javax.swing.JLabel tfHoraFimEx;
    private javax.swing.JFormattedTextField tfHoraInicio;
    private javax.swing.JTextField tfKmEntrada;
    private javax.swing.JTextField tfKmSaida;
    // End of variables declaration//GEN-END:variables
    private String placa;
    private String clienteCpfCnpj;
    private int valor;
    
    private OrdemDeServico os;
}