/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina;

import java.awt.CardLayout;
import oficina.classes.Funcionario;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;
import oficina.forms.FormBuscaPanel;
import oficina.forms.FormCarroPanel;
import oficina.forms.FormOsPanel;
import oficina.forms.FormPessoaPanel;

/**
 *
 * @author Filipe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public MenuPrincipal(Funcionario f) {
        initComponents();
        
        this.funcionario = f;
        
        panelPessoa = new FormPessoaPanel(f);
        panelCarro = new FormCarroPanel(f);
        panelOs = new FormOsPanel(funcionario);
        panelBusca = new FormBuscaPanel();
        
        panelMid.add(panelPessoa, "pessoa");
        panelMid.add(panelCarro, "carro");
        panelMid.add(panelOs, "os");
        panelMid.add(panelBusca, "busca");
        ((CardLayout) panelMid.getLayout()).show(panelMid, "pessoa");

        panelMid.setPreferredSize(panelPessoa.getPreferredSize());
        this.pack();
        
        this.setLocationRelativeTo(null);
        lbNomeText.setText(funcionario.getNome());
        lbUsuarioText.setText(""+funcionario.getCodFuncionario());
        lbPermissaoText.setText("Atendente");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMidHolder = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelMidHolderInside = new javax.swing.JPanel();
        panelMid = new javax.swing.JPanel();
        panelBottom = new javax.swing.JPanel();
        lbIconUsuario = new javax.swing.JLabel();
        paneTextHolder = new javax.swing.JPanel();
        paneUsuario = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbNomeText = new javax.swing.JLabel();
        lbUsuario = new javax.swing.JLabel();
        lbUsuarioText = new javax.swing.JLabel();
        panelPermissao = new javax.swing.JPanel();
        lbPermissao = new javax.swing.JLabel();
        lbPermissaoText = new javax.swing.JLabel();
        panelLeft = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btCadPessoa = new javax.swing.JButton();
        btCadCarro = new javax.swing.JButton();
        btCadOs = new javax.swing.JButton();
        btBusca = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(200, 200));

        panelMidHolder.setLayout(new javax.swing.BoxLayout(panelMidHolder, javax.swing.BoxLayout.PAGE_AXIS));

        panelMid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMid.setMinimumSize(new java.awt.Dimension(220, 220));
        panelMid.setPreferredSize(new java.awt.Dimension(220, 220));
        panelMid.setLayout(new java.awt.CardLayout());
        panelMidHolderInside.add(panelMid);

        jScrollPane1.setViewportView(panelMidHolderInside);

        panelMidHolder.add(jScrollPane1);

        getContentPane().add(panelMidHolder, java.awt.BorderLayout.CENTER);

        panelBottom.setLayout(new javax.swing.BoxLayout(panelBottom, javax.swing.BoxLayout.LINE_AXIS));

        lbIconUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbIconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/login.png"))); // NOI18N
        panelBottom.add(lbIconUsuario);

        paneTextHolder.setLayout(new javax.swing.BoxLayout(paneTextHolder, javax.swing.BoxLayout.PAGE_AXIS));

        paneUsuario.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setText("Nome: ");
        paneUsuario.add(lbNome);

        lbNomeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeText.setText("nomeUsuario(bd)");
        paneUsuario.add(lbNomeText);

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUsuario.setText("Usuário: ");
        paneUsuario.add(lbUsuario);

        lbUsuarioText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUsuarioText.setText("usuario(bd)");
        paneUsuario.add(lbUsuarioText);

        paneTextHolder.add(paneUsuario);

        panelPermissao.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbPermissao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPermissao.setText("Permissão: ");
        panelPermissao.add(lbPermissao);

        lbPermissaoText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPermissaoText.setText("permissaoUsuario(bd)");
        panelPermissao.add(lbPermissaoText);

        paneTextHolder.add(panelPermissao);

        panelBottom.add(paneTextHolder);

        getContentPane().add(panelBottom, java.awt.BorderLayout.PAGE_END);

        panelLeft.setLayout(new javax.swing.BoxLayout(panelLeft, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        btCadPessoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/pessoaFisica.png"))); // NOI18N
        btCadPessoa.setToolTipText("Cadastro de Pessoa Física");
        btCadPessoa.setMaximumSize(new java.awt.Dimension(110, 110));
        btCadPessoa.setMinimumSize(new java.awt.Dimension(110, 110));
        btCadPessoa.setPreferredSize(new java.awt.Dimension(110, 110));
        btCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(btCadPessoa);

        btCadCarro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/car.png"))); // NOI18N
        btCadCarro.setToolTipText("Cadastro de Carro");
        btCadCarro.setMaximumSize(new java.awt.Dimension(110, 110));
        btCadCarro.setMinimumSize(new java.awt.Dimension(110, 110));
        btCadCarro.setPreferredSize(new java.awt.Dimension(110, 110));
        btCadCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadCarroActionPerformed(evt);
            }
        });
        jPanel1.add(btCadCarro);

        btCadOs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/checklist.png"))); // NOI18N
        btCadOs.setToolTipText("Cadastro de Ordem de Serviço");
        btCadOs.setMaximumSize(new java.awt.Dimension(110, 110));
        btCadOs.setMinimumSize(new java.awt.Dimension(110, 110));
        btCadOs.setPreferredSize(new java.awt.Dimension(110, 110));
        btCadOs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadOsActionPerformed(evt);
            }
        });
        jPanel1.add(btCadOs);

        btBusca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/search.png"))); // NOI18N
        btBusca.setToolTipText("Busca");
        btBusca.setMaximumSize(new java.awt.Dimension(110, 110));
        btBusca.setMinimumSize(new java.awt.Dimension(110, 110));
        btBusca.setPreferredSize(new java.awt.Dimension(110, 110));
        btBusca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscaActionPerformed(evt);
            }
        });
        jPanel1.add(btBusca);

        panelLeft.add(jPanel1);

        getContentPane().add(panelLeft, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadPessoaActionPerformed
        /*FormPessoaPanel f;

        f = new FormPessoaPanel();
        f.setVisible(true);*/
        ((CardLayout) panelMid.getLayout()).show(panelMid, "pessoa");
        panelMid.setPreferredSize(panelPessoa.getPreferredSize());
    }//GEN-LAST:event_btCadPessoaActionPerformed

    private void btCadCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadCarroActionPerformed
        /*FormCarro c;

        c = new FormCarro();
        c.setVisible(true);*/
        ((CardLayout) panelMid.getLayout()).show(panelMid, "carro");
        panelMid.setPreferredSize(panelCarro.getPreferredSize());
    }//GEN-LAST:event_btCadCarroActionPerformed

    private void btCadOsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadOsActionPerformed
        /*FormOs os;

        os = new FormOs();
        os.setVisible(true);*/
        ((CardLayout) panelMid.getLayout()).show(panelMid, "os");
        panelMid.setPreferredSize(panelOs.getPreferredSize());
    }//GEN-LAST:event_btCadOsActionPerformed

    private void btBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscaActionPerformed
        /*FormBusca b = new FormBusca();
        b.setVisible(true);*/
        ((CardLayout) panelMid.getLayout()).show(panelMid, "busca");
        panelMid.setPreferredSize(panelBusca.getPreferredSize());
    }//GEN-LAST:event_btBuscaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBusca;
    private javax.swing.JButton btCadCarro;
    private javax.swing.JButton btCadOs;
    private javax.swing.JButton btCadPessoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbIconUsuario;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeText;
    private javax.swing.JLabel lbPermissao;
    private javax.swing.JLabel lbPermissaoText;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbUsuarioText;
    private javax.swing.JPanel paneTextHolder;
    private javax.swing.JPanel paneUsuario;
    private javax.swing.JPanel panelBottom;
    private javax.swing.JPanel panelLeft;
    private javax.swing.JPanel panelMid;
    private javax.swing.JPanel panelMidHolder;
    private javax.swing.JPanel panelMidHolderInside;
    private javax.swing.JPanel panelPermissao;
    // End of variables declaration//GEN-END:variables
    private Funcionario funcionario;
    
    private FormPessoaPanel panelPessoa;
    private FormCarroPanel panelCarro;
    private FormOsPanel panelOs;
    private FormBuscaPanel panelBusca;
}
