/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina;

/**
 *
 * @author Filipe
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public MenuPrincipal(Funcionario l) {
        initComponents();
        this.setLocationRelativeTo(null);
        lbUsuarioText.setText(l.getCodFuncionario());
        //lbPermissaoText.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelTitulo = new javax.swing.JPanel();
        lbMenu = new javax.swing.JLabel();
        panelUsuario = new javax.swing.JPanel();
        lbIconUsuario = new javax.swing.JLabel();
        paneTextHolder = new javax.swing.JPanel();
        paneUsuario = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbNomeText = new javax.swing.JLabel();
        panelNome = new javax.swing.JPanel();
        lbUsuario = new javax.swing.JLabel();
        lbUsuarioText = new javax.swing.JLabel();
        panelPermissao = new javax.swing.JPanel();
        lbPermissao = new javax.swing.JLabel();
        lbPermissaoText = new javax.swing.JLabel();
        panelBotoes = new javax.swing.JPanel();
        btCadPessoa = new javax.swing.JButton();
        btCadCarro = new javax.swing.JButton();
        btCadOs = new javax.swing.JButton();
        btBusca = new javax.swing.JButton();
        panelSeparatorRight = new javax.swing.JPanel();
        panelSeparatorLeft = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setPreferredSize(new java.awt.Dimension(300, 360));
        setResizable(false);

        panelTitulo.setToolTipText("Menu");

        lbMenu.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lbMenu.setText("Menu Principal");
        panelTitulo.add(lbMenu);

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelUsuario.setLayout(new javax.swing.BoxLayout(panelUsuario, javax.swing.BoxLayout.LINE_AXIS));

        lbIconUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbIconUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/login.png"))); // NOI18N
        panelUsuario.add(lbIconUsuario);

        paneTextHolder.setLayout(new javax.swing.BoxLayout(paneTextHolder, javax.swing.BoxLayout.PAGE_AXIS));

        paneUsuario.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setText("Nome: ");
        paneUsuario.add(lbNome);

        lbNomeText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbNomeText.setText("nomeUsuario(bd)");
        paneUsuario.add(lbNomeText);

        paneTextHolder.add(paneUsuario);

        panelNome.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbUsuario.setText("Usuário: ");
        panelNome.add(lbUsuario);

        lbUsuarioText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbUsuarioText.setText("usuario(bd)");
        panelNome.add(lbUsuarioText);

        paneTextHolder.add(panelNome);

        panelPermissao.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lbPermissao.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPermissao.setText("Permissão: ");
        panelPermissao.add(lbPermissao);

        lbPermissaoText.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lbPermissaoText.setText("permissaoUsuario(bd)");
        panelPermissao.add(lbPermissaoText);

        paneTextHolder.add(panelPermissao);

        panelUsuario.add(paneTextHolder);

        getContentPane().add(panelUsuario, java.awt.BorderLayout.PAGE_END);

        panelBotoes.setMinimumSize(new java.awt.Dimension(220, 220));
        panelBotoes.setPreferredSize(new java.awt.Dimension(220, 220));
        panelBotoes.setLayout(new java.awt.GridLayout(2, 3));

        btCadPessoa.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/pessoaFisica.png"))); // NOI18N
        btCadPessoa.setToolTipText("Cadastro de Pessoa Física");
        btCadPessoa.setMaximumSize(new java.awt.Dimension(110, 110));
        btCadPessoa.setMinimumSize(new java.awt.Dimension(110, 110));
        btCadPessoa.setPreferredSize(new java.awt.Dimension(110, 110));
        btCadPessoa.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btCadPessoaMouseClicked(evt);
            }
        });
        panelBotoes.add(btCadPessoa);

        btCadCarro.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadCarro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/car.png"))); // NOI18N
        btCadCarro.setToolTipText("Cadastro de Carro");
        btCadCarro.setMaximumSize(new java.awt.Dimension(110, 110));
        btCadCarro.setMinimumSize(new java.awt.Dimension(110, 110));
        btCadCarro.setPreferredSize(new java.awt.Dimension(110, 110));
        btCadCarro.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btCadCarroMouseClicked(evt);
            }
        });
        panelBotoes.add(btCadCarro);

        btCadOs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btCadOs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/checklist.png"))); // NOI18N
        btCadOs.setToolTipText("Cadastro de Ordem de Serviço");
        btCadOs.setMaximumSize(new java.awt.Dimension(110, 110));
        btCadOs.setMinimumSize(new java.awt.Dimension(110, 110));
        btCadOs.setPreferredSize(new java.awt.Dimension(110, 110));
        btCadOs.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btCadOsMouseClicked(evt);
            }
        });
        panelBotoes.add(btCadOs);

        btBusca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btBusca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oficina/resources/search.png"))); // NOI18N
        btBusca.setToolTipText("Busca");
        btBusca.setMaximumSize(new java.awt.Dimension(110, 110));
        btBusca.setMinimumSize(new java.awt.Dimension(110, 110));
        btBusca.setPreferredSize(new java.awt.Dimension(110, 110));
        btBusca.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btBuscaMouseClicked(evt);
            }
        });
        panelBotoes.add(btBusca);

        getContentPane().add(panelBotoes, java.awt.BorderLayout.CENTER);
        getContentPane().add(panelSeparatorRight, java.awt.BorderLayout.LINE_END);
        getContentPane().add(panelSeparatorLeft, java.awt.BorderLayout.LINE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCadPessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadPessoaMouseClicked
        FormPessoa f;

        f = new FormPessoa();
        f.setVisible(true);
    }//GEN-LAST:event_btCadPessoaMouseClicked

    private void btCadCarroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadCarroMouseClicked
        FormCarro c;

        c = new FormCarro();
        c.setVisible(true);
    }//GEN-LAST:event_btCadCarroMouseClicked

    private void btCadOsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btCadOsMouseClicked
        FormOs os;

        os = new FormOs();
        os.setVisible(true);
    }//GEN-LAST:event_btCadOsMouseClicked

    private void btBuscaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btBuscaMouseClicked
    {//GEN-HEADEREND:event_btBuscaMouseClicked
        FormBusca b = new FormBusca();
        b.setVisible(true);
    }//GEN-LAST:event_btBuscaMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBusca;
    private javax.swing.JButton btCadCarro;
    private javax.swing.JButton btCadOs;
    private javax.swing.JButton btCadPessoa;
    private javax.swing.JLabel lbIconUsuario;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeText;
    private javax.swing.JLabel lbPermissao;
    private javax.swing.JLabel lbPermissaoText;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JLabel lbUsuarioText;
    private javax.swing.JPanel paneTextHolder;
    private javax.swing.JPanel paneUsuario;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelNome;
    private javax.swing.JPanel panelPermissao;
    private javax.swing.JPanel panelSeparatorLeft;
    private javax.swing.JPanel panelSeparatorRight;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelUsuario;
    // End of variables declaration//GEN-END:variables
}
