/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package oficina;

/**
 *
 * @author Rich
 */
public class VisualizaPessoaFisica extends javax.swing.JFrame {

    /**
     * Creates new form VisualizaPessoaFisica
     */
    public VisualizaPessoaFisica(PessoaFisica cliente) {
                
        initComponents();
        this.setLocationRelativeTo(null);
        lbNomeText.setText(cliente.getNome());
        lbRgText.setText(Integer.toString(cliente.getRG()));
        lbCpfText.setText((cliente.getCPF()));
        lbRuaText.setText(cliente.getRua());
        lbNumeroText.setText(cliente.getEndNumero());
        lbCepText.setText(cliente.getCEP());
        lbBairroText.setText(cliente.getBairro());
        lbCidadeText.setText(cliente.getCidade());
        lbEstadoText.setText(cliente.getEstado());
        lbTelefoneText.setText(cliente.getNumResidencial());
        lbCelularText.setText(cliente.getNumCelular());
        lbEmailText.setText(cliente.getEmail());
        taObsText.setText(cliente.getObservacoes());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelTitulo = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panelInfoRow1 = new javax.swing.JPanel();
        lbNome = new javax.swing.JLabel();
        lbNomeText = new javax.swing.JLabel();
        panelInfoRow2 = new javax.swing.JPanel();
        lbRg = new javax.swing.JLabel();
        lbRgText = new javax.swing.JLabel();
        lbCpf = new javax.swing.JLabel();
        lbCpfText = new javax.swing.JLabel();
        panelInfoRow3 = new javax.swing.JPanel();
        lbRua = new javax.swing.JLabel();
        lbRuaText = new javax.swing.JLabel();
        lbNumero = new javax.swing.JLabel();
        lbNumeroText = new javax.swing.JLabel();
        lbCep = new javax.swing.JLabel();
        lbCepText = new javax.swing.JLabel();
        panelInfoRow4 = new javax.swing.JPanel();
        lbBairro = new javax.swing.JLabel();
        lbBairroText = new javax.swing.JLabel();
        lbCidade = new javax.swing.JLabel();
        lbCidadeText = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        lbEstadoText = new javax.swing.JLabel();
        panelInfoRow5 = new javax.swing.JPanel();
        lbTelefone = new javax.swing.JLabel();
        lbTelefoneText = new javax.swing.JLabel();
        lbCelular = new javax.swing.JLabel();
        lbCelularText = new javax.swing.JLabel();
        panelInfoRow6 = new javax.swing.JPanel();
        lbEmail = new javax.swing.JLabel();
        lbEmailText = new javax.swing.JLabel();
        panelInfoRow7 = new javax.swing.JPanel();
        lbObs = new javax.swing.JLabel();
        panelInfoRow8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taObsText = new javax.swing.JTextArea();
        panelBotoes = new javax.swing.JPanel();
        btSair = new javax.swing.JButton();

        setTitle("Visualização de Pessoa Física");
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        lbTitulo.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lbTitulo.setText("Visualização de Pessoa Física");
        panelTitulo.add(lbTitulo);

        getContentPane().add(panelTitulo);

        lbNome.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNome.setText("Nome: ");
        panelInfoRow1.add(lbNome);
        panelInfoRow1.add(lbNomeText);

        getContentPane().add(panelInfoRow1);

        lbRg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRg.setText("RG: ");
        panelInfoRow2.add(lbRg);
        panelInfoRow2.add(lbRgText);

        lbCpf.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCpf.setText("CPF: ");
        panelInfoRow2.add(lbCpf);
        panelInfoRow2.add(lbCpfText);

        getContentPane().add(panelInfoRow2);

        lbRua.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbRua.setText("Rua: ");
        panelInfoRow3.add(lbRua);
        panelInfoRow3.add(lbRuaText);

        lbNumero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbNumero.setText("Numero: ");
        panelInfoRow3.add(lbNumero);
        panelInfoRow3.add(lbNumeroText);

        lbCep.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCep.setText("CEP: ");
        panelInfoRow3.add(lbCep);
        panelInfoRow3.add(lbCepText);

        getContentPane().add(panelInfoRow3);

        lbBairro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbBairro.setText("Bairro: ");
        panelInfoRow4.add(lbBairro);
        panelInfoRow4.add(lbBairroText);

        lbCidade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCidade.setText("Cidade: ");
        panelInfoRow4.add(lbCidade);
        panelInfoRow4.add(lbCidadeText);

        lbEstado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEstado.setText("Estado: ");
        panelInfoRow4.add(lbEstado);
        panelInfoRow4.add(lbEstadoText);

        getContentPane().add(panelInfoRow4);

        lbTelefone.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbTelefone.setText("Telefone: ");
        panelInfoRow5.add(lbTelefone);
        panelInfoRow5.add(lbTelefoneText);

        lbCelular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCelular.setText("Celular: ");
        panelInfoRow5.add(lbCelular);
        panelInfoRow5.add(lbCelularText);

        getContentPane().add(panelInfoRow5);

        lbEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbEmail.setText("Email: ");
        panelInfoRow6.add(lbEmail);
        panelInfoRow6.add(lbEmailText);

        getContentPane().add(panelInfoRow6);

        lbObs.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbObs.setText("Observações:");
        panelInfoRow7.add(lbObs);

        getContentPane().add(panelInfoRow7);

        taObsText.setEditable(false);
        taObsText.setColumns(35);
        taObsText.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        taObsText.setLineWrap(true);
        taObsText.setRows(5);
        taObsText.setWrapStyleWord(true);
        jScrollPane1.setViewportView(taObsText);

        panelInfoRow8.add(jScrollPane1);

        getContentPane().add(panelInfoRow8);

        btSair.setText("Sair");
        btSair.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                btSairMouseClicked(evt);
            }
        });
        panelBotoes.add(btSair);

        getContentPane().add(panelBotoes);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSairMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_btSairMouseClicked
    {//GEN-HEADEREND:event_btSairMouseClicked
        this.dispose();
    }//GEN-LAST:event_btSairMouseClicked

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbBairro;
    private javax.swing.JLabel lbBairroText;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbCelularText;
    private javax.swing.JLabel lbCep;
    private javax.swing.JLabel lbCepText;
    private javax.swing.JLabel lbCidade;
    private javax.swing.JLabel lbCidadeText;
    private javax.swing.JLabel lbCpf;
    private javax.swing.JLabel lbCpfText;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailText;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbEstadoText;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeText;
    private javax.swing.JLabel lbNumero;
    private javax.swing.JLabel lbNumeroText;
    private javax.swing.JLabel lbObs;
    private javax.swing.JLabel lbRg;
    private javax.swing.JLabel lbRgText;
    private javax.swing.JLabel lbRua;
    private javax.swing.JLabel lbRuaText;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTelefoneText;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelInfoRow1;
    private javax.swing.JPanel panelInfoRow2;
    private javax.swing.JPanel panelInfoRow3;
    private javax.swing.JPanel panelInfoRow4;
    private javax.swing.JPanel panelInfoRow5;
    private javax.swing.JPanel panelInfoRow6;
    private javax.swing.JPanel panelInfoRow7;
    private javax.swing.JPanel panelInfoRow8;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JTextArea taObsText;
    // End of variables declaration//GEN-END:variables
}
